Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace weddingPlanner.Models {
 public abstract class BaseEntity {}
	public class User : BaseEntity {

		[Key]
        public int userId {get; set;}   //these variable names must match the table column names exactly
		public string firstName {get; set;}
         public string lastName {get; set;}
        public string email {get; set;}
        public string password {get; set;}
        public DateTime createdAt {get; set;}
        public DateTime updatedAt {get; set;}
        public List<UserWedding> UserWedding {get; set;}
        public User(){
            UserWedding = new List<UserWedding>();
        }
    }
    }

Models/UserViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace weddingPlanner.Models{
    public class UserViewModel : BaseEntity{
        [Required(ErrorMessage = "Please enter your first name")]
        [RegularExpression("^[a-zA-Z]+$")]
        [MinLength(2, ErrorMessage = "First name must be at least 2 characters!")]
        [Display(Name = "First Name:")]
        public string firstName {get; set;}

        [Required(ErrorMessage ="Please enter your last name")]
        [RegularExpression("^[a-zA-Z]+$")]
        [MinLength(2, ErrorMessage="Last name must be at least 2 characters!")]
        [Display(Name = "Last Name:")]
        public string lastName{get; set;}
        
        [Required(ErrorMessage = "Please enter an E-mail")]
        [EmailAddress(ErrorMessage="Please enter a valid E-mail address")]
        [Display(Name = "E-mail:")]
        public string email {get; set;}

        [Required(ErrorMessage = "Please enter a password")]
        [Compare("passwordCheck", ErrorMessage = "Passwords must match!")]
        [MinLength(8, ErrorMessage = "Password must be at least 8 characters")]
        [DataType(DataType.Password)]
        [Display(Name = "Password:")]
        public string password {get; set;}
          
        [Required(ErrorMessage = "Please confirm password")]
        [Compare("password", ErrorMessage = "Passwords must match!")]
        [MinLength(8, ErrorMessage = "Password must be at least 8 characters")]
        [DataType(DataType.Password)]
        [Display(Name = "Password:")]
        public string passwordCheck {get; set;}
    }
}

Models/loginViewModel.cs
 using System;
using System.ComponentModel.DataAnnotations;
 
 namespace weddingPlanner.Models{
    public class loginViewModel : BaseEntity{
 
 [Required(ErrorMessage = "Please enter an E-mail")]
        [EmailAddress(ErrorMessage="Please enter a valid E-mail address")]
        [Display(Name = "E-mail:")]
        public string email {get; set;}
        
        [Required(ErrorMessage = "Please enter a password")]
        [MinLength(8, ErrorMessage = "Password must be at least 8 characters")]
        [DataType(DataType.Password)]
        [Display(Name = "Password:")]
        public string password {get; set;}

    }
 }

Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using weddingPlanner.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace weddingPlanner.Controllers
{
    public class userController : Controller
    {
        private weddingPlannerContext _context;
    public userController(weddingPlannerContext context)
    {
         _context = context;

    } 
        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult addUser(UserViewModel user){
            if(ModelState.IsValid){
                if(_context.users.SingleOrDefault(a => a.email== user.email)!=null){
                    TempData["Error"]="Email already exists";
                    return RedirectToAction("Index");
                }
            PasswordHasher<UserViewModel> Hasher = new PasswordHasher<UserViewModel>();
                user.password = Hasher.HashPassword(user, user.password);
                User newUser = new User{
                    firstName = user.firstName,
                    lastName = user.lastName,
                    email = user.email,
                    password = user.password,
                };
                _context.Add(newUser);
                _context.SaveChanges();
                User nu = _context.users.SingleOrDefault(u => u.email == user.email);
                HttpContext.Session.SetInt32("id", nu.userId);
                return RedirectToAction("dash");
            }
            return View("Index");
        }
            public IActionResult Login(loginViewModel user){
                if(ModelState.IsValid){
                    User oneUser = _context.users.SingleOrDefault(u => u.email == user.email);
                    if(oneUser != null){
                if(user.email != null && user.password != null){
                        var Hasher = new PasswordHasher<loginViewModel>();
                    if(0 != Hasher.VerifyHashedPassword(user, oneUser.password, user.password)){
                        HttpContext.Session.SetInt32("id", oneUser.userId);
                        return RedirectToAction("dash");
                        }
                     }
                    }
                }
                 TempData["Error"]="User does not exist";
                    return View("Index");
            }
            public IActionResult dash(){
                  List<Wedding> allWeddings =_context.weddings.Include(u => u.UserWedding).ThenInclude(u => u.User).ToList();
                    ViewBag.allWeddings = allWeddings;
                    ViewBag.userId = HttpContext.Session.GetInt32("id");
                    return View("dashboard");
            }
           
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/User/Index.cshtml
@{
    ViewData["Title"] = "Register";
}
@model weddingPlanner.Models.UserViewModel

 
<div asp-validation-summary="All"></div>
@if(TempData["error"] != null){
    <p>@TempData["error"]</p>
}
<div class="form-group">
<fieldset>
    <legend><h2>Registration</h2></legend>
    <form asp-controller="user" asp-action="addUser" method="post">
    <label asp-for="firstName"></label>
    <input class ="form-control"asp-for="firstName"/><br>
    <label asp-for="lastName"></label>
    <input class="form-control" asp-for="lastName"/><br>
    <label asp-for="email"></label>
    <input class="form-control" asp-for="email"/><br>
    <label asp-for="password"></label>
    <input class="form-control" asp-for="password"/><br>
    <label asp-for="passwordCheck"></label>
    <input class="form-control" asp-for="passwordCheck"/><br>
    <button type="submit" class="btn btn-primary">Create new User</button>
</form>
</fieldset>
</div>
@Html.Partial("login")

Views/User/dashboard.cshtml
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><a href="/">Log Out</a></li>
    </ul>
  </div>
</nav>
<h1>Welcome to the Wedding Planner</h1>
<table class="table table-striped table-bordered">
    <thead>
        <th>Wedding</th>
        <th>Date</th>
        <th>Guest</th>
        <th>Action</th>
    </thead>
@foreach(Wedding wedding in @ViewBag.allWeddings){
    <tr>
          <td><a asp-controller="wedding" asp-action="newWed" asp-route-id="@wedding.weddingId">@wedding.wedderOne and @wedding.wedderTwo</a></td>
          <td>@wedding.date.ToString("MMM dd, yyyy")</td>
          <td>@wedding.UserWedding.Count</td>
          @if(wedding.createdBy == @ViewBag.userId){
              <td><a asp-controller="wedding" asp-action="delete" asp-route-id="@wedding.weddingId">Delete</a></td>
          }
          else{      
                bool found = false;
          @foreach(UserWedding plan in @wedding.UserWedding){
            if(@plan.User != null){
                if((int) @plan.User.userId == (int)@ViewBag.userId){
                    found = true;
                }
            }
          }
            if(!found){
                <td><a asp-controller="wedding" asp-action="rsvp" asp-route-id="@wedding.weddingId">RSVP</a></td>
            }
            else{
                <td><a asp-controller="wedding" asp-action="unRsvp" asp-route-id="@wedding.weddingId">Un-RSVP</a></td>
            }
        }
    </tr>
}

</table
<button><a class="btn btn-primary" role="button" asp-controller="wedding" asp-action="addWeddingLink">New Wedding</a></button>

Views/User/login.cshtml
@model weddingPlanner.Models.loginViewModel
<div class="form-group">
<fieldset>
   <span asp-validation-for="email"></span><br>
   <span asp-validation-for="password"></span>
   @if(TempData["error"] != null){
    <p>@TempData["error"]</p>
}
    <legend><h2>Log In</h2></legend>
    <form asp-action="Login">
    <label asp-for="email"></label>
    <input class ="form-control" asp-for="email"/><br>
    <label asp-for="password"></label>
    <input class ="form-control" asp-for="password"/><br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
</fieldset>
</div>